const CDN = 'https://images.squarespace-cdn.com/content/v1/5f5679c017299d539905d4a6/';

export const posts = [
  {
    id: 1,
    slug: 'clean-air-act-la',
    category: 'Policy Analysis',
    categoryColor: 'blue',
    date: 'March 14, 2024',
    title: "What the Clean Air Act Doesn't Cover: The Case for Local Air Monitoring in LA",
    excerpt: "Federal standards set the floor for air quality regulation — but in a sprawling, traffic-dense metro like Los Angeles, that floor isn't always enough. Our team examines the gaps and what local governments can do about them.",
    author: 'Marcus W. & Yuna P.',
    readTime: '8 min read',
    featured: true,
    img: CDN + '1743019200250-M8G9GGZNKLQRNYOSKOD5/SUFSstreetview.jpg',
    body: [
      { type: 'p', text: "The Clean Air Act of 1970 — and its major amendments in 1977 and 1990 — remains the backbone of air quality regulation in the United States. It established National Ambient Air Quality Standards (NAAQS) for six \"criteria\" pollutants: particulate matter, ozone, carbon monoxide, sulfur dioxide, nitrogen dioxide, and lead. In theory, any community in America can rely on these standards as a legal guarantee of baseline air quality." },
      { type: 'p', text: "In practice, Los Angeles exposes the limits of a one-size-fits-all federal approach. LA's geography — a basin ringed by mountains that trap pollution — combined with the highest vehicle density in the country and a patchwork of industrial land uses means that the aggregate monitors the South Coast Air Quality Management District (SCAQMD) uses to report compliance often miss the hyper-local variation that determines whether someone living next to a freeway in Boyle Heights breathes the same air as someone in Brentwood. They don't." },
      { type: 'h2', text: 'The Monitor Gap' },
      { type: 'p', text: "Federal law requires SCAQMD to maintain a network of monitoring stations to measure compliance with NAAQS. The district operates roughly 40 stations across a 10,743-square-mile jurisdiction covering LA, Orange, Riverside, and San Bernardino counties. That's one monitor per ~270 square miles. For regulatory purposes, a single monitor may represent air quality across entire ZIP codes — or in some cases, across multiple ZIP codes with very different pollution profiles." },
      { type: 'p', text: "Research consistently shows that pollution levels vary dramatically within distances of less than a mile near major emission sources. A 2021 study published in Environmental Health Perspectives found that children attending schools within 150 meters of a freeway in Los Angeles experienced particulate matter exposures 30–40% higher than EPA monitors in their same ZIP code reported. The monitors weren't wrong — they were just not where the children were." },
      { type: 'h2', text: "What Falls Between the Cracks" },
      { type: 'p', text: "Three categories of pollutants and sources expose the federal framework's limits most acutely in LA:" },
      { type: 'p', text: "**Ultrafine particles (UFPs).** NAAQS covers PM2.5 (particles smaller than 2.5 micrometers) but not UFPs (particles smaller than 0.1 micrometers). UFPs penetrate deeper into lung tissue and are more readily absorbed into the bloodstream. Near-freeway UFP concentrations in Los Angeles can be ten times higher than background levels just two kilometers away. The EPA has discussed regulating UFPs for over a decade but has not acted, citing data gaps — a self-reinforcing problem since no federal monitoring mandate means few data are being collected." },
      { type: 'p', text: "**Warehouse and goods-movement emissions.** LA's Inland Empire has become one of the largest logistics hubs in the world, with millions of diesel truck trips annually. Diesel PM and nitrogen oxides from freight corridors have been linked in several studies to elevated rates of asthma and cardiovascular disease in communities along the 710 and 60 freeways. SCAQMD's monitoring network was not designed for this concentration of point-line sources and does not have the spatial resolution to attribute community-level health impacts to specific corridors." },
      { type: 'p', text: "**Wildfire smoke.** The NAAQS framework was built around anthropogenic pollution from stationary and mobile sources. Wildfire smoke — now a near-annual reality in Southern California — involves PM2.5 spikes that can exceed federal standards by an order of magnitude for days at a time, disproportionately in communities far from the fixed monitor network. Current regulatory triggers and public health advisories depend on monitor data that may not reflect what vulnerable populations are actually breathing." },
      { type: 'h2', text: 'The Local Monitoring Solution' },
      { type: 'p', text: "Low-cost sensor networks offer a partial but meaningful supplement to federal monitoring. Devices like the PurpleAir sensor, which costs around $250, have proliferated across Los Angeles. There are now over 1,200 PurpleAir sensors in LA County alone — far outnumbering regulatory monitors and providing near-real-time data at the block level." },
      { type: 'p', text: "The accuracy limitations of low-cost sensors are real: they read high in humid conditions and require calibration against regulatory instruments. But several California air districts, including the Bay Area AQMD, have begun integrating calibrated low-cost sensor data into their public health communication systems. SCAQMD has run pilot programs but has not yet committed to a district-wide supplemental monitoring network." },
      { type: 'h2', text: 'Policy Recommendations' },
      { type: 'p', text: "Based on our review of the literature and interviews with air quality researchers at UCLA and Caltech, we recommend the following:" },
      { type: 'p', text: "First, LA County should fund a permanent network of calibrated low-cost sensors at a density of at least one per square mile in communities within 500 meters of major freight corridors, freeways with average daily traffic above 100,000 vehicles, and industrial zones with permitted emissions above specified thresholds." },
      { type: 'p', text: "Second, SCAQMD should develop and publish a protocol for integrating low-cost sensor data into public health advisories — not as a replacement for regulatory monitoring, but as a supplemental early-warning layer." },
      { type: 'p', text: "Third, the LA County Department of Public Health should work with the county's office of the Chief Science Officer to establish a community air monitoring data platform accessible to the public, schools, and healthcare providers — modeled on the Bay Area's AirNow+ system." },
      { type: 'p', text: "The Clean Air Act did something extraordinary: it created a legal right to breathable air and gave federal agencies the tools to enforce it. But the statute was designed for the pollution problems of 1970. The geography of exposure in contemporary Los Angeles — shaped by freight logistics, wildfire, and a legacy of environmental injustice in siting — requires supplemental tools the federal law doesn't provide. Local governments have both the authority and the obligation to fill that gap." },
    ],
  },
  {
    id: 2,
    slug: 'lab-to-legislature',
    category: 'Career & Professional',
    categoryColor: 'teal',
    date: 'February 28, 2024',
    title: "From Lab to Legislature: What I Learned Interning at the California Governor's Office of Planning and Research",
    excerpt: "SPG alum Nadia Flores spent a summer translating environmental science into policy language for state officials. Here's what surprised her, what she wish she had known, and what every science student should understand about how government actually works.",
    author: 'Nadia F., SPG Alum',
    readTime: '11 min read',
    featured: true,
    img: CDN + '1745790270571-RGM5KHS8W5XIQYG48KFM/unnamed.jpg',
    body: [
      { type: 'p', text: "I applied to the California Governor's Office of Planning and Research (OPR) fellowship on a bit of a whim. I was a second-year PhD student in environmental science at UCLA, three months into my dissertation research on coastal wetland carbon sequestration, and I had started to feel a nagging question I couldn't shake: who reads this?" },
      { type: 'p', text: "OPR runs a science fellows program that places graduate students and postdocs in state agencies to support evidence-based policymaking. The application involved a writing sample, an interview, and a statement of why I wanted to translate science into policy. I wrote something earnest about wanting my research to matter beyond the journal page. They accepted me. I deferred a field season and spent twelve weeks in Sacramento." },
      { type: 'p', text: "What follows is what I wish someone had told me before I walked into that building." },
      { type: 'h2', text: 'The Pace Is Not What You Expect' },
      { type: 'p', text: "In academia, slow is often a virtue. You take the time to be right. You hedge your claims because the data warrant hedging. You respond to reviewer comments over months and publish, if you're lucky, a year after submission." },
      { type: 'p', text: "Government does not work this way. My first week, I was asked to produce a two-page summary of the state of the science on sea-level rise projections for the California coast — for a briefing happening in four days. I spent the first day panicking, the second day drafting, the third day revising based on feedback from my supervisor, and the fourth day watching a Deputy Secretary use my summary in a conversation with federal officials. It was terrifying and electric in equal measure." },
      { type: 'p', text: "The lesson is not that rigor doesn't matter in government — it does, enormously. The lesson is that \"rigorous\" and \"exhaustive\" are not the same thing. A decision-maker at a briefing needs the three things that are most important, stated clearly, with the key uncertainty flagged. They do not need the literature review." },
      { type: 'h2', text: 'Nobody Knows What a Confidence Interval Is' },
      { type: 'p', text: "This is slightly unfair. Some people in government are extraordinarily sophisticated consumers of science. But the modal audience for a science summary in a government context — a legislative aide, a department budget analyst, a deputy secretary covering four different issue areas — has limited statistical training and unlimited competing priorities." },
      { type: 'p', text: "I had to learn to translate uncertainty into plain language without lying about it. Instead of \"the 95% confidence interval spans 0.4°C to 1.2°C,\" I learned to say \"scientists broadly agree warming will fall in this range, with current best estimates around 0.8°C — but natural variability means real-world outcomes could be somewhat higher or lower.\" It means the same thing to a scientist. It communicates something meaningful to everyone else." },
      { type: 'p', text: "The deeper challenge is that uncertainty, communicated poorly, becomes a political tool. \"Scientists don't even agree\" is a sentence I heard several times in contexts where what the science actually showed was strong consensus with a bounded range of projections. Learning to communicate the distinction — and to do it quickly, in writing, under time pressure — is a skill that is almost never taught in graduate school." },
      { type: 'h2', text: 'Policy Has a Longer Memory Than Science' },
      { type: 'p', text: "One of the stranger things I encountered was how often officials referenced scientific findings that were five, ten, or fifteen years old. Not because they were unaware of newer work — but because those older findings had made it into statutes, regulations, environmental impact report templates, or formal guidance documents, and changing them required a formal process that science alone couldn't drive." },
      { type: 'p', text: "This taught me something important: getting a finding into policy is not the end of the job. The finding has to be maintained, updated, and defended as the literature moves. Scientists are generally not in the room for that ongoing process. Which means findings can calcify into regulatory assumptions long past their scientific sell-by date — or, conversely, can be prematurely retired by actors who would prefer not to act on them." },
      { type: 'h2', text: 'What You Can Do Now' },
      { type: 'p', text: "I came back to UCLA with a different sense of what my dissertation is for. Not a different dissertation — the same one, studying the same wetlands, asking the same questions. But I now write the policy implications section with a specific audience in mind: a California Natural Resources Agency analyst who has fifteen minutes to read it and a decision to make." },
      { type: 'p', text: "If I could go back and advise my first-year self, I'd say three things. First: take a science communication course or workshop before you feel ready. The skills compound. Second: read one government document per week — an EIR, a rulemaking notice, a legislative analysis — to understand the genre you're trying to influence. Third: apply for internships and fellowships before you feel qualified. Everyone in my cohort felt unqualified. None of us were." },
      { type: 'p', text: "SPG's advocacy training and policy writing workshops were, I can say now, genuinely useful preparation for what I found in Sacramento. Not because they made me an expert in state government — they didn't, and couldn't — but because they gave me practice being a scientist in a room where science is one input among many. That turns out to be exactly where the work happens." },
    ],
  },
  {
    id: 3,
    slug: 'scientists-as-advocates',
    category: 'Science Communication',
    categoryColor: 'gold',
    date: 'February 5, 2024',
    title: 'Why Scientists Make Bad Advocates (And How to Fix It)',
    excerpt: "Scientists are trained to hedge, qualify, and present uncertainty. Advocates need to be clear, direct, and persuasive. These aren't incompatible — but the translation requires practice. Here are the specific habits to build.",
    author: 'Priya N.',
    readTime: '6 min read',
    featured: false,
    img: CDN + '1749621414650-FNBWS2ZA7AOXFZGHSV8S/20250528_171737.jpg',
    body: [
      { type: 'p', text: "Let me describe a scene that plays out, with minor variations, in almost every science advocacy training I have ever attended. A researcher — usually a PhD student or postdoc, often extremely smart, with a decade of domain expertise — is asked to make the case for a policy intervention in two minutes. They begin with background. They define terms. They introduce caveats. They note that the evidence, while substantial, is not definitive, and that further research is needed. By the time they get to the recommendation, the two minutes are up." },
      { type: 'p', text: "This is not a failure of intelligence or commitment. It is a failure of genre. Scientists are trained to perform a specific kind of communication — one that is comprehensive, qualified, and deferential to uncertainty. That form of communication is exactly right for a journal article, a dissertation, or a lab meeting. It is exactly wrong for a legislative briefing, a public comment, or a meeting with a city council aide." },
      { type: 'h2', text: 'The Hedging Habit' },
      { type: 'p', text: "The single most common problem I see in scientist-advocates is what I call the hedging habit: the compulsion to qualify every claim before it can land. \"The evidence suggests\" when you mean \"we know.\" \"It's possible that\" when you mean \"it is likely that.\" \"Some researchers argue\" when you mean \"the scientific consensus holds.\"" },
      { type: 'p', text: "Hedging serves a real purpose in scientific writing. It accurately communicates epistemic status. But in advocacy contexts, it accomplishes something different: it gives the listener permission not to act. If even the expert presenting the evidence sounds uncertain, why should a policymaker take political risk on it?" },
      { type: 'p', text: "The fix is not to lie — not to claim certainty you don't have. It is to calibrate your language to what the evidence actually justifies, and then to say that thing directly. \"The evidence is strong that X causes Y\" is accurate when it is accurate. Say it that way." },
      { type: 'h2', text: 'The Background Problem' },
      { type: 'p', text: "Scientists also tend to front-load background. Before making the case for a policy, they explain the science. Before explaining the science, they explain the methodology. Before the methodology, they explain why the question is interesting. By the time they arrive at the thing they actually want to say, the audience has mentally checked out." },
      { type: 'p', text: "Advocacy communication works in the opposite direction. Lead with the recommendation. Follow with the evidence. End with why the audience should care. This structure — sometimes called the \"inverted pyramid\" from journalism — feels deeply unnatural to scientists. It feels like you're skipping steps, asserting conclusions without laying groundwork. But your audience is not a journal reviewer. They do not need the groundwork before they can evaluate the claim. They need to know what you want them to do." },
      { type: 'h2', text: 'What to Practice' },
      { type: 'p', text: "These habits are correctable with deliberate practice. Here are three exercises that have made the biggest difference for SPG members in our advocacy training:" },
      { type: 'p', text: "**The one-sentence policy ask.** Before any meeting or briefing, write the one thing you want your audience to do, believe, or remember, in a single sentence. If you cannot write it, you are not ready to advocate. If you can write it, start your meeting with it." },
      { type: 'p', text: "**The three-layer summary.** Practice describing your evidence in three layers: what we know with high confidence, what we know with moderate confidence, and what we don't yet know. This gives you a structure for communicating uncertainty without leading with it." },
      { type: 'p', text: "**The \"so what\" test.** After every factual claim in your pitch, ask yourself \"so what?\" If you cannot answer that question in one sentence, the claim is probably background that can be cut. Every fact you present should connect, directly and explicitly, to the recommendation you want your audience to act on." },
      { type: 'p', text: "Science and advocacy are not opposites. The best scientific advocates I know are rigorous — often more rigorous than their academic peers about what the evidence does and doesn't show. The difference is that they have learned to separate the question of what the evidence says from the question of how to communicate it to someone who has to make a decision. Those are different skills. Both can be learned." },
    ],
  },
  {
    id: 4,
    slug: 'california-water-guide',
    category: 'Explainer',
    categoryColor: 'purple',
    date: 'January 18, 2024',
    title: "California's Water Budget: A Plain-Language Guide for Scientists",
    excerpt: "State water law in California is famously complicated. This piece strips it down to what you need to know to meaningfully engage with water policy discussions at any level of government.",
    author: 'Jordan K.',
    readTime: '9 min read',
    featured: false,
    img: CDN + '1712213116495-BRN7UD962M7ASUZB55W4/IMG_7812.png',
    body: [
      { type: 'p', text: "California water law is notoriously complex — a layered system of competing rights, byzantine infrastructure, and contested entitlements that has been the subject of litigation almost continuously since the Gold Rush. But the basic structure is more navigable than it appears, and scientists engaging with water policy don't need to be lawyers to participate meaningfully. What follows is the framework I wish someone had given me before I attended my first water board meeting." },
      { type: 'h2', text: 'Where the Water Comes From' },
      { type: 'p', text: "California receives roughly 200 million acre-feet of precipitation in an average year. About 65% of that is lost to evapotranspiration — absorbed by native vegetation or evaporated. The remaining ~71 million acre-feet constitutes the state's developed water supply, though the actual amount available varies enormously from year to year and is declining under climate change." },
      { type: 'p', text: "California divides this supply between three sources: surface water (rivers, lakes, reservoirs), groundwater (aquifers), and recycled water (reclaimed wastewater). The California Department of Water Resources estimates the state currently uses about 42 million acre-feet annually. Agriculture accounts for roughly 80% of that use. Urban and environmental uses split the remainder." },
      { type: 'h2', text: 'How Water Rights Work' },
      { type: 'p', text: "California operates under a dual system of water rights. The older doctrine, \"riparian rights,\" gives landowners adjacent to a water source the right to reasonable use of that water. The more dominant doctrine, \"prior appropriation,\" operates on the principle of \"first in time, first in right\" — senior rights holders get their full allocation before junior rights holders receive any water. In drought years, this can mean that water districts with junior rights receive nothing while senior rights holders are fully satisfied." },
      { type: 'p', text: "The State Water Resources Control Board (SWRCB) administers water rights and can issue curtailment orders limiting diversions when supply is insufficient. During the 2021–2022 drought, the SWRCB issued curtailment orders affecting hundreds of water rights holders across the Sacramento-San Joaquin Delta watershed — the first time such orders had been issued in decades." },
      { type: 'h2', text: 'The Infrastructure' },
      { type: 'p', text: "California moves water through two major systems. The State Water Project (SWP), operated by the Department of Water Resources, is the largest state-built water and power development and conveyance system in the country. It moves water from Northern California to 29 water agencies serving 27 million people through 700 miles of canals, tunnels, and pipelines. The Central Valley Project (CVP), operated by the federal Bureau of Reclamation, serves primarily agricultural users in the Central Valley." },
      { type: 'p', text: "Both systems depend critically on snowpack in the Sierra Nevada as natural storage. As climate change reduces snowpack and shifts precipitation from snow to rain, both systems face serious long-term supply reliability challenges that current infrastructure is not designed to handle." },
      { type: 'h2', text: 'Groundwater: The Recent Revolution' },
      { type: 'p', text: "Until 2014, California was the only western state without meaningful groundwater regulation. Landowners could pump essentially unlimited amounts from the aquifers beneath their property. Decades of over-pumping have depleted major aquifers across the Central Valley, caused measurable land subsidence in the San Joaquin Valley, and degraded water quality in numerous communities." },
      { type: 'p', text: "The Sustainable Groundwater Management Act (SGMA), signed in 2014, changed this. It requires local groundwater sustainability agencies (GSAs) to develop Groundwater Sustainability Plans (GSPs) and achieve sustainable groundwater management by 2040 in critically overdrafted basins. SGMA is the most significant reform of California water law in a century, and it is still being implemented — which means there are ongoing opportunities for scientific input into the process." },
      { type: 'h2', text: 'Where Scientists Can Engage' },
      { type: 'p', text: "Water policy decisions in California happen at multiple scales, all of which accept public comment and scientific input. At the state level, the SWRCB and DWR regularly hold public hearings on rulemaking, water allocation decisions, and infrastructure planning. At the regional level, the nine Regional Water Quality Control Boards oversee water quality and issue permits. At the local level, GSAs are currently in the process of finalizing and implementing groundwater sustainability plans — many of them understaffed and hungry for technical assistance." },
      { type: 'p', text: "The most effective scientific engagement I have seen in water policy has not come from researchers submitting formal comments on rulemakings (though that matters). It has come from scientists showing up to local GSA board meetings, offering to review technical documents, and building ongoing relationships with agency staff. The science-policy gap in water is not primarily an access problem — it is a time and relationship problem. Agencies know they need scientific input. They often don't have the capacity to seek it out. Scientists who show up fill a real need." },
    ],
  },
  {
    id: 5,
    slug: 'career-night-2023',
    category: 'Event Recap',
    categoryColor: 'teal',
    date: 'December 7, 2023',
    title: "Science Policy Career Night 2023: Key Takeaways from Five Professionals",
    excerpt: "At our fall career event, five panelists from the NIH, EPA, LA County, RAND, and a Congressional office answered every question our members had about breaking into science policy. Here are the most important things they said.",
    author: 'SPG Editorial Team',
    readTime: '7 min read',
    featured: false,
    img: CDN + '1701998400183-FUQGRD19MLRILCUJH7DR/IMG_6104.JPG',
    body: [
      { type: 'p', text: "On December 5th, SPG hosted its second annual Science Policy Career Night, bringing together 85 students and five working professionals for an evening of structured Q&A and informal networking. Our panelists came from the National Institutes of Health, the Environmental Protection Agency's Region 9 office, the Los Angeles County Department of Public Health, the RAND Corporation, and a U.S. Congressional office (the staffer requested that the specific office not be named)." },
      { type: 'p', text: "The event ran for two hours. What follows is our editorial team's synthesis of the most significant and most frequently referenced points from the panel discussion." },
      { type: 'h2', text: '1. The PhD Is Not a Prerequisite — But the Skills It Builds Are' },
      { type: 'p', text: "This was perhaps the most frequently discussed topic of the evening. Our panelists represented a range of educational backgrounds: two had PhDs, two had master's degrees, and one had a bachelor's and had entered policy work directly from an undergraduate research position. The consensus was consistent: what matters is not the credential, but the capacity to read and evaluate technical evidence, to communicate it clearly to non-specialists, and to work across disciplinary and institutional boundaries." },
      { type: 'p', text: "The NIH panelist, a health scientist administrator in the Office of Science Policy, put it directly: \"I've worked with people with PhDs who couldn't explain their work to a congressional staffer, and I've worked with people with bachelor's degrees who were extraordinary at it. The degree gives you time to develop these skills — it doesn't automatically give you the skills.\"" },
      { type: 'h2', text: '2. Fellowship Programs Are the Most Reliable Entry Point' },
      { type: 'p', text: "When asked how panelists had gotten their current jobs, every one of them mentioned a fellowship, internship, or temporary appointment as either their direct entry point or a critical stepping stone. Programs mentioned included the AAAS Science and Technology Policy Fellowship, the California Council on Science and Technology (CCST) Science Fellows program, the EPA ORISE fellowship, and several agency-specific rotational programs." },
      { type: 'p', text: "The RAND panelist offered practical advice: \"Fellowship applications are competitive, but less competitive than people think, because most scientists don't apply. The people who get these positions are not uniformly the best scientists in their cohort — they're the scientists who applied.\" Several panelists noted that applying before you feel \"ready\" is almost always the right call." },
      { type: 'h2', text: '3. The Most Important Skill Is Writing — Specifically, Short Writing' },
      { type: 'p', text: "Every panelist, unprompted, mentioned writing when asked what skills they wished they had developed before entering policy work. Not academic writing — the ability to write a clear, well-organized one- or two-page brief for a non-specialist audience under time pressure." },
      { type: 'p', text: "The Congressional staffer was blunt: \"A two-page memo is the genre of government. If you can write a strong two-pager, you can do this work. If you can't, you will struggle, regardless of how good your science is.\" Several panelists mentioned that this is a learnable skill — but that almost no graduate program teaches it, and that practicing it is the only way to develop it." },
      { type: 'h2', text: '4. Relationships Are Built Slowly and Matter Enormously' },
      { type: 'p', text: "The LA County panelist described her career path as \"a fifteen-year slow accumulation of people who knew I was trustworthy and competent.\" She emphasized that policy careers, more than most, are built through ongoing relationships with people who can vouch for you — not through applications alone." },
      { type: 'p', text: "Practical implications: attend public comment hearings, not just to comment but to introduce yourself to agency staff afterward. Reach out to people whose work you admire with a specific, substantive question — not a generic request to \"pick their brain.\" Volunteer for advisory committees. Show up consistently in the spaces where policy gets made, and be someone who brings useful things when you do." },
      { type: 'h2', text: '5. Non-Partisan Doesn\'t Mean Apolitical' },
      { type: 'p', text: "This was the most nuanced conversation of the evening. Every panelist emphasized the importance of being perceived as a credible, non-partisan scientific resource — someone who is trusted across partisan lines because they are seen as honest about what the evidence shows. At the same time, several panelists gently pushed back on the notion that scientific engagement with policy can be fully separated from political context." },
      { type: 'p', text: "The EPA panelist described it as \"knowing which fights to pick and which to stay out of.\" Understanding the political landscape — not in order to play partisan games, but in order to make evidence-based recommendations in a way that is receivable by the people who need to receive them — is a competency that scientists entering policy work need to develop." },
      { type: 'p', text: "SPG will host Career Night again in fall 2024. If you'd like to be notified when applications open, join our mailing list through the Contact page." },
    ],
  },
  {
    id: 6,
    slug: 'lausd-science-curriculum',
    category: 'Policy Analysis',
    categoryColor: 'blue',
    date: 'November 20, 2023',
    title: "LAUSD's Science Curriculum: Strong on Standards, Weak on Science Policy",
    excerpt: "LA Unified meets California science standards, but almost nothing in the K–12 curriculum teaches students how science influences — or doesn't influence — the decisions being made about their lives. That matters.",
    author: 'Amara O. & Sarah C.',
    readTime: '10 min read',
    featured: false,
    img: CDN + '1739536921111-D9OJ4TQZ7M6VB9IC9Y1X/JoanCCSTShowcase.png',
    body: [
      { type: 'p', text: "California's Next Generation Science Standards (NGSS), adopted statewide in 2013 and implemented by the Los Angeles Unified School District over the following several years, represent a genuine improvement in K–12 science education. The standards emphasize scientific practices — asking questions, designing investigations, constructing explanations, engaging in argument from evidence — rather than rote memorization of facts. By most measures, LAUSD's implementation has been reasonable. Students who complete the district's science sequence graduate with a cleaner sense of what scientists do and how scientific knowledge is produced." },
      { type: 'p', text: "What they don't graduate with is any meaningful understanding of how that knowledge does or doesn't influence the decisions that shape their lives. Science policy — how scientific evidence enters (or fails to enter) public decision-making — is essentially absent from the K–12 curriculum in LA Unified. We believe this is a significant gap, and we think it can be addressed without a comprehensive curriculum overhaul." },
      { type: 'h2', text: 'What We Reviewed' },
      { type: 'p', text: "Over the course of the 2022–2023 academic year, our team reviewed the LAUSD Science Scope and Sequence documents for grades 6–12, interviewed eight LAUSD science teachers across four middle schools and four high schools, reviewed the district's current approved instructional materials, and compared LAUSD's approach to the science-society curriculum frameworks adopted by four other large urban districts (New York, Chicago, Houston, and Seattle)." },
      { type: 'p', text: "We were not evaluating the quality of science instruction itself — by most indicators, that quality has improved significantly since NGSS implementation. We were evaluating whether the curriculum, as currently structured, prepares students to be informed participants in the civic conversations that scientific evidence bears on." },
      { type: 'h2', text: 'The Gap We Found' },
      { type: 'p', text: "The NGSS framework includes a strand called \"Science and Engineering Practices\" and a set of \"Crosscutting Concepts\" that are explicitly intended to connect science to broader societal questions. But in practice, LAUSD's implementation of these elements is heavily focused on the internal practices of scientific inquiry — hypothesis generation, experimental design, data analysis — rather than the external question of how scientific knowledge interacts with institutions, politics, and public decision-making." },
      { type: 'p', text: "In our review of scope and sequence documents, we found no required unit or lesson in the 6–12 curriculum explicitly addressing: how regulatory agencies use scientific evidence; how scientific findings are translated into policy recommendations; how political and economic factors interact with scientific knowledge in public decisions; or how citizens can access and evaluate the scientific basis of government decisions affecting them." },
      { type: 'p', text: "Teachers we interviewed were largely aware of this gap and uniformly expressed interest in addressing it — but noted that they lacked time, curriculum support, and instructional materials to do so." },
      { type: 'h2', text: 'What Other Districts Are Doing' },
      { type: 'p', text: "Chicago Public Schools' science curriculum includes a required 10th-grade unit titled \"Science and Society\" that explicitly addresses the relationship between scientific evidence and public policy, using local case studies involving air quality, lead in water, and urban heat islands. Seattle Public Schools has developed elective science courses focused on \"Science, Technology, and Society\" at the high school level. New York City has piloted a \"Science Citizenship\" module in several middle schools, funded through a partnership with Columbia University." },
      { type: 'p', text: "None of these programs is perfect or universally implemented, but each represents a deliberate institutional choice to teach students not just how science works, but how it connects to the world outside the classroom." },
      { type: 'h2', text: 'Our Recommendations' },
      { type: 'p', text: "We are not recommending that LAUSD overhaul its curriculum or reduce time spent on core science content. We are recommending three targeted additions that could be implemented within existing instructional time constraints:" },
      { type: 'p', text: "First, that LAUSD develop or adopt a 2–3 week module on \"science in civic life\" for integration into the 9th or 10th grade science sequence, using California-specific case studies (air quality regulation, Proposition 65, the SGMA groundwater law) to illustrate how scientific evidence enters public decision-making." },
      { type: 'p', text: "Second, that the district partner with local universities and science policy organizations — including UCLA, Caltech, and organizations like SPG — to develop guest-speaker programs and field experiences connecting students with working scientists and science policy professionals." },
      { type: 'p', text: "Third, that the district convene a working group to review how the NGSS crosscutting concept of \"Influence of Science, Engineering, and Technology on Society and the Natural World\" is currently addressed in instructional materials, and identify gaps for targeted intervention." },
      { type: 'p', text: "We recognize that LAUSD faces significant resource constraints and that any new curriculum initiative competes with existing priorities. But preparing students to be scientifically literate citizens — not just to understand how atoms bond, but to understand how the science of air quality shapes the regulations governing the air they breathe — is part of what public education is for. We think this gap is worth closing." },
    ],
  },
];

export const catColors = {
  blue:   { bg: 'var(--ucla-blue-lt)', color: 'var(--ucla-blue)' },
  teal:   { bg: '#e2f4f3', color: '#1D7B74' },
  gold:   { bg: 'var(--gold-lt)', color: 'var(--gold-dk)' },
  purple: { bg: '#f0eef8', color: '#6B52AE' },
};
